
/***********************************************\
 *  Copyright (c) 2010 by Ing.Vladimir Hrusovsky *
 *  Sodalis 2007-2011                            *
 *  http://www.sodalis.sk                        *
 \***********************************************/
    
     
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsDialog.java
 *
 * Created on 17.1.2009, 13:36:29
 */
package sk.magiksoft.sodalis.core.settings;

import sk.magiksoft.sodalis.core.factory.IconFactory;
import sk.magiksoft.sodalis.core.locale.LocaleManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * @author wladimiiir
 */
public class SettingsDialog extends javax.swing.JDialog {

    private DefaultComboBoxModel model = new DefaultComboBoxModel();

    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        initComponents2();
    }

    public void addSettingsPanel(SettingsPanel panel) {
        model.addElement(panel);
    }

    public void reloadSettings() {
        for (int i = 0; i < model.getSize(); i++) {
            SettingsPanel panel = (SettingsPanel) model.getElementAt(i);

            panel.reloadSettings();
        }
    }

    private void initComponents2() {
        cbxSettings.setRenderer(new DefaultListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (c instanceof JLabel && value instanceof SettingsPanel) {
                    ((JLabel) c).setText(((SettingsPanel) value).getSettingsPanelName());
                }
                c.setPreferredSize(new Dimension(c.getPreferredSize().width, 30));

                return c;
            }
        });

        cbxSettings.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                SettingsPanel settingsPanel = (SettingsPanel) cbxSettings.getSelectedItem();

                if (settingsPanel != null) {
                    showSettingsPanel(settingsPanel);
                }
            }
        });
        cbxSettings.setFont(cbxSettings.getFont().deriveFont(Font.BOLD, 13f));
    }

    private void showSettingsPanel(SettingsPanel settingsPanel) {
        pnlCenter.removeAll();
        pnlCenter.add(settingsPanel.getSwingComponent(), BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }

    private boolean saveSettings() {
        for (int i = 0; i < model.getSize(); i++) {
            SettingsPanel panel = (SettingsPanel) model.getElementAt(i);

            if (!panel.saveSettings()) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDialog = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        cbxSettings = new javax.swing.JComboBox();
        pnlCenter = new javax.swing.JPanel();
        pnlButtonPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDialog.setLayout(new java.awt.BorderLayout());

        pnlNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pnlNorth.setLayout(new java.awt.BorderLayout());

        cbxSettings.setModel(model);
        cbxSettings.setFocusable(false);
        pnlNorth.add(cbxSettings, java.awt.BorderLayout.PAGE_START);

        pnlDialog.add(pnlNorth, java.awt.BorderLayout.NORTH);

        pnlCenter.setLayout(new java.awt.BorderLayout());
        pnlDialog.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDialog, java.awt.BorderLayout.CENTER);

        pnlButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnSave.setIcon(IconFactory.getInstance().getIcon("ok"));
        btnSave.setText(LocaleManager.getString("saveAction"));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButtonPanel.add(btnSave);

        btnCancel.setIcon(IconFactory.getInstance().getIcon("cancel"));
        btnCancel.setText(LocaleManager.getString("cancelAction"));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtonPanel.add(btnCancel);

        getContentPane().add(pnlButtonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (saveSettings()) {
            setVisible(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbxSettings;
    private javax.swing.JPanel pnlButtonPanel;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlDialog;
    private javax.swing.JPanel pnlNorth;
    // End of variables declaration//GEN-END:variables
}