
package sk.magiksoft.sodalis.updater;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateServiceService", targetNamespace = "http://updater.sodalis.magiksoft.sk/", wsdlLocation = "http://localhost:8999/sodalis/UpdateService?wsdl")
public class UpdateServiceService
    extends Service
{

    private final static URL UPDATESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATESERVICESERVICE_EXCEPTION;
    private final static QName UPDATESERVICESERVICE_QNAME = new QName("http://updater.sodalis.magiksoft.sk/", "UpdateServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8999/sodalis/UpdateService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATESERVICESERVICE_WSDL_LOCATION = url;
        UPDATESERVICESERVICE_EXCEPTION = e;
    }

    public UpdateServiceService() {
        super(__getWsdlLocation(), UPDATESERVICESERVICE_QNAME);
    }

    public UpdateServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATESERVICESERVICE_QNAME, features);
    }

    public UpdateServiceService(URL wsdlLocation) {
        super(wsdlLocation, UPDATESERVICESERVICE_QNAME);
    }

    public UpdateServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATESERVICESERVICE_QNAME, features);
    }

    public UpdateServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateService
     */
    @WebEndpoint(name = "UpdateServicePort")
    public UpdateService getUpdateServicePort() {
        return super.getPort(new QName("http://updater.sodalis.magiksoft.sk/", "UpdateServicePort"), UpdateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateService
     */
    @WebEndpoint(name = "UpdateServicePort")
    public UpdateService getUpdateServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://updater.sodalis.magiksoft.sk/", "UpdateServicePort"), UpdateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATESERVICESERVICE_EXCEPTION!= null) {
            throw UPDATESERVICESERVICE_EXCEPTION;
        }
        return UPDATESERVICESERVICE_WSDL_LOCATION;
    }

}
