
package sk.magiksoft.sodalis.updater;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateService", targetNamespace = "http://updater.sodalis.magiksoft.sk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateService {


    /**
     * 
     * @param properties
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUpdate", targetNamespace = "http://updater.sodalis.magiksoft.sk/", className = "sk.magiksoft.sodalis.updater.CreateUpdate")
    @ResponseWrapper(localName = "createUpdateResponse", targetNamespace = "http://updater.sodalis.magiksoft.sk/", className = "sk.magiksoft.sodalis.updater.CreateUpdateResponse")
    @Action(input = "http://updater.sodalis.magiksoft.sk/UpdateService/createUpdateRequest", output = "http://updater.sodalis.magiksoft.sk/UpdateService/createUpdateResponse")
    public String createUpdate(
        @WebParam(name = "properties", targetNamespace = "")
        sk.magiksoft.sodalis.updater.CreateUpdate.Properties properties);

}
